### ISSUE TITLE
x and : are  not registered as a possible value to use to calculate

### ISSUE THREAD

**Issue by MadisonMadi** [lGrom/calculator-commands#2]
![image](https://github.com/lGrom/calculator-commands/assets/17278366/351e3836-2dd4-4723-9400-b845560f04c9)
 x is not recognised as a valid function or variable and x is another way to multiple like *
 
 and the : is an unknown operator this : is another way to divide like /

**Comment by gnattily** [comment]
X is commonly used as a variable name. Though this calculator does not support variables, adding it as an operator would still confuse users and give seemingly unrelated error.

I would add that colon feature, but this repository isn't really maintained anymore. There are better, more capable mods out there that get updated more frequently. Sorry.
